version: 2.1
orbs:
  matlab: mathworks/matlab@dev:alpha
jobs:
  build_and_test_matlab:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: "cd test/matlab/shared; diary('/tmp/matlabDiary.log'); runAllAmslaTests();"
      - store_test_results:
          path: /tmp/testResults
      - store_artifacts:
          path: /tmp/matlabDiary.log

  performance:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: "cd test/matlab/shared; diary('/tmp/perfDiary.log'); runAllAmslaPerformanceTests();"
      - store_artifacts:
          path: /tmp/testResults
      - store_artifacts:
          path: /tmp/perfDiary.log

  build_and_test_cpp:
    docker:
      - image: apicciau/opencl_ubuntu:latest
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Debug ..
            make VERBOSE=1
      - run:
          name: Run all the tests
          command: |
            mkdir /tmp/amsla_test
            cd build/test/cpp
            GTEST_OUTPUT="xml:/tmp/amsla_test/test_amsla_common.xml" ./common/test_amsla_common
            GTEST_OUTPUT="xml:/tmp/amsla_test/test_amsla_datastructures.xml" ./common/test_amsla_datastructures
      - store_test_results:
          path: /tmp/amsla_test

workflows:
  version: 2.1
  run_all_tests:
    jobs:
      - build_and_test_matlab
      - build_and_test_cpp
      - performance
