version: 2.1
orbs:
  matlab: mathworks/matlab@dev:alpha
jobs:
  build_and_test_matlab:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: "cd test/matlab/shared; diary('/tmp/matlabDiary.log'); runAllAmslaTests();"
      - store_test_results:
          path: /tmp/testResults
      - store_artifacts:
          path: /tmp/matlabDiary.log

  performance:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: "cd test/matlab/shared; diary('/tmp/perfDiary.log'); runAllAmslaPerformanceTests();"
      - store_artifacts:
          path: /tmp/testResults
      - store_artifacts:
          path: /tmp/perfDiary.log

  build_and_test_cpp:
    docker:
      - image: apicciau/opencl_ubuntu:latest
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Debug ..
            make VERBOSE=1
      - run:
          name: Run all the tests
          command: |
            mkdir /tmp/amsla_test
            cd build/test/cpp
            ctest --verbose --no-compress-output -T Test
            mv ./Testing/**/Test.xml /tmp/amsla_test/test_amsla.xml
      - store_test_results:
          path: /tmp/amsla_test

  build_and_coverage_cpp:
    docker:
      - image: apicciau/opencl_ubuntu:latest
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mkdir build && cd build
            cmake -DCODE_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug ..
            make VERBOSE=1
      - run:
          name: Run all the tests
          command: |
            mkdir /tmp/amsla_test
            cd build/test/cpp
            ctest --verbose --no-compress-output
      - run:
          name: Collect code coverage
          command: |
            cd build/test/cpp
            lcov --directory . --capture --output-file ./code_coverage.info -rc lcov_branch_coverage=1
            lcov --remove ./code_coverage.info '/usr/*' --output-file ./code_coverage.info
            lcov --remove ./code_coverage.info '7/*' --output-file ./code_coverage.info
            lcov --list ./code_coverage.info
            bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

workflows:
  version: 2.1
  run_all_tests:
    jobs:
      - build_and_test_matlab
      - build_and_test_cpp
      - build_and_coverage_cpp
      - performance
