version: 2.1
orbs:
  matlab: mathworks/matlab@0.1
jobs:
  build_and_test_matlab:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: "cd test/matlab/shared; diary('/tmp/matlabDiary.log'); runAllAmslaTests();"
      - store_test_results:
          path: /tmp/testResults
      - store_artifacts:
          path: /tmp/matlabDiary.log

  performance:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: "cd test/matlab/shared; diary('/tmp/perfDiary.log'); runAllAmslaPerformanceTests();"
      - store_artifacts:
          path: /tmp/testResults
      - store_artifacts:
          path: /tmp/perfDiary.log

  build_and_test_cpp:
    docker:
      - image: apicciau/opencl_ubuntu:latest
    steps:
      - checkout
      - run:
          name: Build and run all tests
          command: |
            python3 setup.py -dt
            mkdir /tmp/amsla_test
            find ./build -name 'Test.xml' -exec mv {} /tmp/amsla_test/test_amsla.xml \;
      - store_test_results:
          path: /tmp/amsla_test

  build_and_coverage_cpp:
    docker:
      - image: apicciau/opencl_ubuntu:latest
    steps:
      - checkout
      - run:
          name: Build and collect code coverage
          command: |
            python3 setup.py -dct
            bash <(curl -s https://codecov.io/bash) -f ./build/code_coverage.info || echo "Codecov did not collect coverage reports"

workflows:
  version: 2.1
  run_all_tests:
    jobs:
      - build_and_test_matlab
      - build_and_test_cpp
      - build_and_coverage_cpp
      - performance
